Talks page
pycontw/pycon_archive_past_website pull request #9
Opened 2021-07-11 09:59 UTC by MozixReality

1. fetch talk & tutorial pages
2. readme change pip to pipenv

2021-07-11 14:28 UTC, josix requested changes

2021-07-11 14:28 UTC, josix commented on main.py
> +Visited_page = []
It is a better habit for naming variable following [PEP 8 coding style convention](https://www.python.org/dev/peps/pep-0008/). For example, the constant variable should be written in all capital letters with underscores separating words, i.e. PYCON_YEAR, PYCON_URL, WRITTEN_URL...

2021-07-11 14:28 UTC, josix commented on README.md
> +## Pipenv
IMO, we should have a more meaningful title like `Setup development environment`, `Installing dependencies`

2021-07-11 14:28 UTC, josix commented on main.py
> +Visited_page = []
It is a better habit for naming variable following PEP 8 coding style convention. For example, [the constant](https://www.python.org/dev/peps/pep-0008/#constants) variable should be written in all capital letters with underscores separating words, i.e. `PYCON_YEAR`, `PYCON_URL`, `WRITTEN_URL`... and [the variable](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names) should be written in lowercase, with words separated by underscores

2021-07-11 14:28 UTC, josix commented on main.py
>  def GetPage(path):
Same as above, we should follow PEP8 coding style convention to name function name in lowercase, with words separated by underscores. [Here is the ref](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names)

2021-07-11 14:28 UTC, josix commented on main.py
>      print(path)
Not sure if this is necessary for keep this printing remain. We can remove it if it don't bring any helpful information or make this printing info more completely as logging message by using logging tool like [loguru](https://github.com/Delgan/loguru), [built-in logging module](https://docs.python.org/3/library/logging.html), etc.

2021-07-11 14:28 UTC, josix commented on main.py
>      request = requests.get(Pycon_url + path)
We cloud introduce [pathlib](https://docs.python.org/3/library/pathlib.html) here for helping us dealing with the path related operation

2021-07-12 11:54 UTC, MozixReality commented
review file change

2021-07-28 17:44 UTC, josix approved these changes

2021-07-28 17:47 UTC, merged

2021-07-28 17:48 UTC, josix commented
Hello @MozixReality, thanks for your work and sorry for the late review. I'll merge this PR and we will have some refactor works to do.